using System.Text.Json;
using System.Text.Json.Serialization;
using CampaignManager.Contracts.Admin;
using CampaignManager.Contracts.Campaigns;
using CampaignManager.Contracts.Catalogs;
using CampaignManager.Contracts.Characters;
using CampaignManager.Contracts.Encounters;
using CampaignManager.Contracts.Files;
using CampaignManager.Contracts.Identity;
using CampaignManager.Contracts.Music;
using CampaignManager.Contracts.Platform;
using CampaignManager.Contracts.Profile;
using CampaignManager.Contracts.Scenarios;

namespace CampaignManager.Contracts;

/// <summary>
/// Единственный способ сериализовать DTO API: сгенерированный контекст вместо рефлексии,
/// чтобы клиент работал и под AOT (мобильное приложение, D4). Новый DTO модуля
/// добавляется сюда атрибутом. Сервер ставит этот контекст первым в цепочку резолверов.
/// Enum'ы — строками с именем члена, как в колонках и документах (SCHEMA, правило 5).
/// </summary>
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, UseStringEnumConverter = true)]
[JsonSerializable(typeof(PingResponse))]
[JsonSerializable(typeof(StoredFileDto))]
[JsonSerializable(typeof(AddExternalFileRequest))]
[JsonSerializable(typeof(OrphanFilesReport))]
[JsonSerializable(typeof(DeleteOrphansRequest))]
[JsonSerializable(typeof(DeleteOrphansResponse))]
[JsonSerializable(typeof(MeResponse))]
[JsonSerializable(typeof(HomeDto))]
[JsonSerializable(typeof(IReadOnlyList<CampaignSummaryDto>))]
[JsonSerializable(typeof(CampaignSummaryDto))]
[JsonSerializable(typeof(CampaignDetailsDto))]
[JsonSerializable(typeof(CampaignMemberDto))]
[JsonSerializable(typeof(CampaignInput))]
[JsonSerializable(typeof(JoinCampaignRequest))]
[JsonSerializable(typeof(UpdateMemberRequest))]
[JsonSerializable(typeof(CampaignJournalDto))]
[JsonSerializable(typeof(CampaignSessionDto))]
[JsonSerializable(typeof(CampaignSessionInput))]
[JsonSerializable(typeof(CharacterDto))]
[JsonSerializable(typeof(CharacterSavedDto))]
[JsonSerializable(typeof(SetPortraitRequest))]
[JsonSerializable(typeof(SetStatusRequest))]
[JsonSerializable(typeof(IReadOnlyList<PartyMemberDto>))]
[JsonSerializable(typeof(IReadOnlyList<InvestigatorDto>))]
[JsonSerializable(typeof(CampaignManager.Core.Characters.CharacterSheet))]
[JsonSerializable(typeof(CreateCharacterRequest))]
[JsonSerializable(typeof(CharacterCreatedDto))]
[JsonSerializable(typeof(CreationContextDto))]
[JsonSerializable(typeof(IReadOnlyList<CharacterSummaryDto>))]
[JsonSerializable(typeof(EncounterDto))]
[JsonSerializable(typeof(IReadOnlyList<EncounterSummaryDto>))]
[JsonSerializable(typeof(StartEncounterRequest))]
[JsonSerializable(typeof(EncounterSavedDto))]
[JsonSerializable(typeof(CampaignManager.Core.Encounters.EncounterState))]
[JsonSerializable(typeof(SkillDto))]
[JsonSerializable(typeof(CatalogList<SkillDto>))]
[JsonSerializable(typeof(CatalogFile<SkillDto>))]
[JsonSerializable(typeof(OccupationDto))]
[JsonSerializable(typeof(CatalogList<OccupationDto>))]
[JsonSerializable(typeof(CatalogFile<OccupationDto>))]
[JsonSerializable(typeof(WeaponDto))]
[JsonSerializable(typeof(CatalogList<WeaponDto>))]
[JsonSerializable(typeof(CatalogFile<WeaponDto>))]
[JsonSerializable(typeof(SpellDto))]
[JsonSerializable(typeof(CatalogList<SpellDto>))]
[JsonSerializable(typeof(CatalogFile<SpellDto>))]
[JsonSerializable(typeof(BookDto))]
[JsonSerializable(typeof(CatalogList<BookDto>))]
[JsonSerializable(typeof(CatalogFile<BookDto>))]
[JsonSerializable(typeof(ItemDto))]
[JsonSerializable(typeof(CatalogList<ItemDto>))]
[JsonSerializable(typeof(CatalogFile<ItemDto>))]
[JsonSerializable(typeof(CreatureDto))]
[JsonSerializable(typeof(CatalogList<CreatureDto>))]
[JsonSerializable(typeof(CatalogFile<CreatureDto>))]
[JsonSerializable(typeof(CatalogImportReport))]
[JsonSerializable(typeof(ProfileDto))]
[JsonSerializable(typeof(UpdateDisplayNameRequest))]
[JsonSerializable(typeof(SubmitKeeperApplicationRequest))]
[JsonSerializable(typeof(PreferencesDto))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(AdminSummaryDto))]
[JsonSerializable(typeof(IReadOnlyList<AdminUserDto>))]
[JsonSerializable(typeof(AdminUserDto))]
[JsonSerializable(typeof(ChangeRoleRequest))]
[JsonSerializable(typeof(IReadOnlyList<KeeperApplicationDto>))]
[JsonSerializable(typeof(KeeperApplicationDto))]
[JsonSerializable(typeof(RejectApplicationRequest))]
[JsonSerializable(typeof(MusicTrackDto))]
[JsonSerializable(typeof(CatalogList<MusicTrackDto>))]
[JsonSerializable(typeof(CatalogFile<MusicTrackDto>))]
[JsonSerializable(typeof(PinnedTagsDto))]
[JsonSerializable(typeof(PinnedTagsRequest))]
[JsonSerializable(typeof(MusicPoolDto))]
[JsonSerializable(typeof(ScenarioListDto))]
[JsonSerializable(typeof(ScenarioInput))]
[JsonSerializable(typeof(ScenarioTextInput))]
[JsonSerializable(typeof(ScenarioSavedDto))]
[JsonSerializable(typeof(ScenarioDto))]
[JsonSerializable(typeof(ScenarioLocationDto))]
[JsonSerializable(typeof(LocationInput))]
[JsonSerializable(typeof(ScenarioCheckDto))]
[JsonSerializable(typeof(CheckInput))]
[JsonSerializable(typeof(KeyFactDto))]
[JsonSerializable(typeof(KeyFactInput))]
[JsonSerializable(typeof(HandoutDto))]
[JsonSerializable(typeof(HandoutInput))]
[JsonSerializable(typeof(ScenarioCreatureDto))]
[JsonSerializable(typeof(ScenarioCreatureInput))]
[JsonSerializable(typeof(ScenarioItemDto))]
[JsonSerializable(typeof(ScenarioItemInput))]
[JsonSerializable(typeof(NpcCastInput))]
[JsonSerializable(typeof(AddPregenRequest))]
[JsonSerializable(typeof(ReorderRequest))]
[JsonSerializable(typeof(ScenarioImportReport))]
[JsonSerializable(typeof(LocationMusicInput))]
[JsonSerializable(typeof(HandoutScreenDto))]
[JsonSerializable(typeof(IReadOnlyList<ScenarioRunDto>))]
public sealed partial class ContractsJsonContext : JsonSerializerContext;
