namespace CampaignManager.Core.Tests.Parsers;

/// <summary>
///     Все различные значения колонок «Дальность», «Атак», «Боезапас» и «Стоимость» каталога
///     оружия (таблица XVII, стр. 399–402) — вместе с тем, что разборщик дал на них, когда
///     заполнял разобранные колонки. Источник — миграция <c>WeaponStatsBackfill</c>
///     (коммит 9a4e0d7, удалена при схлопывании истории в eded94a); сам каталог живёт только
///     в базе. Сгенерировано скриптом из текста миграции, руками не править.
/// </summary>
internal static class WeaponCatalogRows
{
    /// <summary>Колонка «Range»: 28 значений.</summary>
    public static TheoryData<string, string> Range => new()
    {
        { "10 метров", """{"Kind":2,"BaseMeters":10,"Bands":null,"ThrowDivisor":null,"RawText":"10 метров","IsParsed":true}""" },
        { "10/20/50 метров", """{"Kind":3,"BaseMeters":10,"Bands":[10,20,50],"ThrowDivisor":null,"RawText":"10/20/50 метров","IsParsed":true}""" },
        { "100 метров", """{"Kind":2,"BaseMeters":100,"Bands":null,"ThrowDivisor":null,"RawText":"100 метров","IsParsed":true}""" },
        { "110 метров", """{"Kind":2,"BaseMeters":110,"Bands":null,"ThrowDivisor":null,"RawText":"110 метров","IsParsed":true}""" },
        { "15 метров", """{"Kind":2,"BaseMeters":15,"Bands":null,"ThrowDivisor":null,"RawText":"15 метров","IsParsed":true}""" },
        { "150 метров", """{"Kind":2,"BaseMeters":150,"Bands":null,"ThrowDivisor":null,"RawText":"150 метров","IsParsed":true}""" },
        { "2 метра", """{"Kind":2,"BaseMeters":2,"Bands":null,"ThrowDivisor":null,"RawText":"2 метра","IsParsed":true}""" },
        { "20 метров", """{"Kind":2,"BaseMeters":20,"Bands":null,"ThrowDivisor":null,"RawText":"20 метров","IsParsed":true}""" },
        { "200 метров", """{"Kind":2,"BaseMeters":200,"Bands":null,"ThrowDivisor":null,"RawText":"200 метров","IsParsed":true}""" },
        { "2000 метров", """{"Kind":2,"BaseMeters":2000,"Bands":null,"ThrowDivisor":null,"RawText":"2000 метров","IsParsed":true}""" },
        { "25 метров", """{"Kind":2,"BaseMeters":25,"Bands":null,"ThrowDivisor":null,"RawText":"25 метров","IsParsed":true}""" },
        { "250 метров", """{"Kind":2,"BaseMeters":250,"Bands":null,"ThrowDivisor":null,"RawText":"250 метров","IsParsed":true}""" },
        { "3 метра", """{"Kind":2,"BaseMeters":3,"Bands":null,"ThrowDivisor":null,"RawText":"3 метра","IsParsed":true}""" },
        { "30 метров", """{"Kind":2,"BaseMeters":30,"Bands":null,"ThrowDivisor":null,"RawText":"30 метров","IsParsed":true}""" },
        { "3000 метров", """{"Kind":2,"BaseMeters":3000,"Bands":null,"ThrowDivisor":null,"RawText":"3000 метров","IsParsed":true}""" },
        { "5 метров", """{"Kind":2,"BaseMeters":5,"Bands":null,"ThrowDivisor":null,"RawText":"5 метров","IsParsed":true}""" },
        { "5/10 метров", """{"Kind":3,"BaseMeters":5,"Bands":[5,10],"ThrowDivisor":null,"RawText":"5/10 метров","IsParsed":true}""" },
        { "50 метров", """{"Kind":2,"BaseMeters":50,"Bands":null,"ThrowDivisor":null,"RawText":"50 метров","IsParsed":true}""" },
        { "500 метров", """{"Kind":2,"BaseMeters":500,"Bands":null,"ThrowDivisor":null,"RawText":"500 метров","IsParsed":true}""" },
        { "60 метров", """{"Kind":2,"BaseMeters":60,"Bands":null,"ThrowDivisor":null,"RawText":"60 метров","IsParsed":true}""" },
        { "80 метров", """{"Kind":2,"BaseMeters":80,"Bands":null,"ThrowDivisor":null,"RawText":"80 метров","IsParsed":true}""" },
        { "90 метров", """{"Kind":2,"BaseMeters":90,"Bands":null,"ThrowDivisor":null,"RawText":"90 метров","IsParsed":true}""" },
        { "Касание", """{"Kind":1,"BaseMeters":null,"Bands":null,"ThrowDivisor":null,"RawText":"Касание","IsParsed":true}""" },
        { "На месте", """{"Kind":5,"BaseMeters":null,"Bands":null,"ThrowDivisor":null,"RawText":"На месте","IsParsed":true}""" },
        { "Нет", """{"Kind":0,"BaseMeters":null,"Bands":null,"ThrowDivisor":null,"RawText":"Нет","IsParsed":true}""" },
        { "СИЛ / 5 метров", """{"Kind":4,"BaseMeters":null,"Bands":null,"ThrowDivisor":5,"RawText":"СИЛ / 5 метров","IsParsed":true}""" },
        { "СИЛ/5м", """{"Kind":4,"BaseMeters":null,"Bands":null,"ThrowDivisor":5,"RawText":"СИЛ/5м","IsParsed":true}""" },
        { "Сил/5м", """{"Kind":4,"BaseMeters":null,"Bands":null,"ThrowDivisor":5,"RawText":"Сил/5м","IsParsed":true}""" },
    };

    /// <summary>Колонка «Attacks»: 17 значений.</summary>
    public static TheoryData<string, string> Attacks => new()
    {
        { "1", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1","IsParsed":true}""" },
        { "1 (2)", """{"ShotsPerRound":1,"MaxShotsPerRound":2,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1 (2)","IsParsed":true}""" },
        { "1 (2) или непр. огонь", """{"ShotsPerRound":1,"MaxShotsPerRound":2,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":true,"IsSingleUse":false,"RawText":"1 (2) или непр. огонь","IsParsed":true}""" },
        { "1 (2) или очередями по 3", """{"ShotsPerRound":1,"MaxShotsPerRound":2,"RoundsPerAttack":null,"AllowsBurst":true,"BurstSize":3,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1 (2) или очередями по 3","IsParsed":true}""" },
        { "1 (3)", """{"ShotsPerRound":1,"MaxShotsPerRound":3,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1 (3)","IsParsed":true}""" },
        { "1 (3) или непр. огонь", """{"ShotsPerRound":1,"MaxShotsPerRound":3,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":true,"IsSingleUse":false,"RawText":"1 (3) или непр. огонь","IsParsed":true}""" },
        { "1 или 2", """{"ShotsPerRound":1,"MaxShotsPerRound":2,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1 или 2","IsParsed":true}""" },
        { "1 или непр. огонь", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":true,"IsSingleUse":false,"RawText":"1 или непр. огонь","IsParsed":true}""" },
        { "1 или очередями по 3", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":true,"BurstSize":3,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1 или очередями по 3","IsParsed":true}""" },
        { "1/2", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":2,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1/2","IsParsed":true}""" },
        { "1/3", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":3,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1/3","IsParsed":true}""" },
        { "1/4", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":4,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"1/4","IsParsed":true}""" },
        { "2", """{"ShotsPerRound":2,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"2","IsParsed":true}""" },
        { "На месте", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":true,"RawText":"На месте","IsParsed":true}""" },
        { "Непр. огонь", """{"ShotsPerRound":null,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":true,"IsSingleUse":false,"RawText":"Непр. огонь","IsParsed":true}""" },
        { "Нет", """{"ShotsPerRound":null,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":false,"RawText":"Нет","IsParsed":true}""" },
        { "Одноразовый", """{"ShotsPerRound":1,"MaxShotsPerRound":null,"RoundsPerAttack":null,"AllowsBurst":false,"BurstSize":null,"AllowsFullAuto":false,"IsSingleUse":true,"RawText":"Одноразовый","IsParsed":true}""" },
    };

    /// <summary>Колонка «Ammo»: 33 значений.</summary>
    public static TheoryData<string, string> Ammo => new()
    {
        { "", """{"Capacity":null,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"","IsParsed":true}""" },
        { "1", """{"Capacity":1,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"1","IsParsed":true}""" },
        { "10", """{"Capacity":10,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"10","IsParsed":true}""" },
        { "11", """{"Capacity":11,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"11","IsParsed":true}""" },
        { "15", """{"Capacity":15,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"15","IsParsed":true}""" },
        { "15/30", """{"Capacity":15,"CapacityOptions":[15,30],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"15/30","IsParsed":true}""" },
        { "17", """{"Capacity":17,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"17","IsParsed":true}""" },
        { "2", """{"Capacity":2,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"2","IsParsed":true}""" },
        { "20", """{"Capacity":20,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"20","IsParsed":true}""" },
        { "20/30/32", """{"Capacity":20,"CapacityOptions":[20,30,32],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"20/30/32","IsParsed":true}""" },
        { "20/30/50", """{"Capacity":20,"CapacityOptions":[20,30,50],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"20/30/50","IsParsed":true}""" },
        { "200", """{"Capacity":200,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"200","IsParsed":true}""" },
        { "25 доз", """{"Capacity":25,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"25 доз","IsParsed":true}""" },
        { "250", """{"Capacity":250,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"250","IsParsed":true}""" },
        { "3", """{"Capacity":3,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"3","IsParsed":true}""" },
        { "30", """{"Capacity":30,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"30","IsParsed":true}""" },
        { "30/100", """{"Capacity":30,"CapacityOptions":[30,100],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"30/100","IsParsed":true}""" },
        { "30/200", """{"Capacity":30,"CapacityOptions":[30,200],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"30/200","IsParsed":true}""" },
        { "32", """{"Capacity":32,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"32","IsParsed":true}""" },
        { "4000", """{"Capacity":4000,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"4000","IsParsed":true}""" },
        { "47/97", """{"Capacity":47,"CapacityOptions":[47,97],"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"47/97","IsParsed":true}""" },
        { "5", """{"Capacity":5,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"5","IsParsed":true}""" },
        { "6", """{"Capacity":6,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"6","IsParsed":true}""" },
        { "7", """{"Capacity":7,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"7","IsParsed":true}""" },
        { "8", """{"Capacity":8,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"8","IsParsed":true}""" },
        { "Автоподача", """{"Capacity":null,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":true,"IsSuppliedSeparately":false,"RawText":"Автоподача","IsParsed":true}""" },
        { "Варьирует", """{"Capacity":null,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Варьирует","IsParsed":false}""" },
        { "Минимум 10", """{"Capacity":10,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Минимум 10","IsParsed":true}""" },
        { "Однораз.", """{"Capacity":1,"CapacityOptions":null,"IsSingleUse":true,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Однораз.","IsParsed":true}""" },
        { "Одноразовая", """{"Capacity":1,"CapacityOptions":null,"IsSingleUse":true,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Одноразовая","IsParsed":true}""" },
        { "Одноразовый", """{"Capacity":1,"CapacityOptions":null,"IsSingleUse":true,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Одноразовый","IsParsed":true}""" },
        { "Отдельно", """{"Capacity":null,"CapacityOptions":null,"IsSingleUse":false,"IsBeltFed":false,"IsSuppliedSeparately":true,"RawText":"Отдельно","IsParsed":true}""" },
        { "Только 1", """{"Capacity":1,"CapacityOptions":null,"IsSingleUse":true,"IsBeltFed":false,"IsSuppliedSeparately":false,"RawText":"Только 1","IsParsed":true}""" },
    };

    /// <summary>Колонка «Cost»: 75 значений.</summary>
    public static TheoryData<string, string> Cost => new()
    {
        { "$0,05/0,50", """{"Cost1920":0.05,"CostModern":0.50,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$0,05/0,50","IsParsed":true}""" },
        { "$0,50/3", """{"Cost1920":0.50,"CostModern":3,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$0,50/3","IsParsed":true}""" },
        { "$0,65 – 5,25", """{"Cost1920":0.65,"CostModern":null,"IsApproximate1920":true,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$0,65 – 5,25","IsParsed":true}""" },
        { "$1,98", """{"Cost1920":1.98,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$1,98","IsParsed":true}""" },
        { "$1/10", """{"Cost1920":1,"CostModern":10,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$1/10","IsParsed":true}""" },
        { "$1/20 коробка", """{"Cost1920":1,"CostModern":20,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$1/20 коробка","IsParsed":true}""" },
        { "$1/25", """{"Cost1920":1,"CostModern":25,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$1/25","IsParsed":true}""" },
        { "$10/100", """{"Cost1920":10,"CostModern":100,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$10/100","IsParsed":true}""" },
        { "$1000/20 000", """{"Cost1920":1000,"CostModern":20000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$1000/20 000","IsParsed":true}""" },
        { "$12/55", """{"Cost1920":12,"CostModern":55,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$12/55","IsParsed":true}""" },
        { "$13/70", """{"Cost1920":13,"CostModern":70,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$13/70","IsParsed":true}""" },
        { "$15/100", """{"Cost1920":15,"CostModern":100,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$15/100","IsParsed":true}""" },
        { "$15/200", """{"Cost1920":15,"CostModern":200,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$15/200","IsParsed":true}""" },
        { "$15/75", """{"Cost1920":15,"CostModern":75,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$15/75","IsParsed":true}""" },
        { "$1500/—", """{"Cost1920":1500,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":true,"RawText":"$1500/—","IsParsed":true}""" },
        { "$19/150", """{"Cost1920":19,"CostModern":150,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$19/150","IsParsed":true}""" },
        { "$2,50", """{"Cost1920":2.50,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2,50","IsParsed":true}""" },
        { "$2/15", """{"Cost1920":2,"CostModern":15,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2/15","IsParsed":true}""" },
        { "$2/4", """{"Cost1920":2,"CostModern":4,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2/4","IsParsed":true}""" },
        { "$2/5", """{"Cost1920":2,"CostModern":5,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2/5","IsParsed":true}""" },
        { "$2/6", """{"Cost1920":2,"CostModern":6,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2/6","IsParsed":true}""" },
        { "$20/200", """{"Cost1920":20,"CostModern":200,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$20/200","IsParsed":true}""" },
        { "$20/350", """{"Cost1920":20,"CostModern":350,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$20/350","IsParsed":true}""" },
        { "$200", """{"Cost1920":200,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$200","IsParsed":true}""" },
        { "$2000/14 000", """{"Cost1920":2000,"CostModern":14000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$2000/14 000","IsParsed":true}""" },
        { "$25/100", """{"Cost1920":25,"CostModern":100,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$25/100","IsParsed":true}""" },
        { "$25/150", """{"Cost1920":25,"CostModern":150,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$25/150","IsParsed":true}""" },
        { "$25/190", """{"Cost1920":25,"CostModern":190,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$25/190","IsParsed":true}""" },
        { "$25/200", """{"Cost1920":25,"CostModern":200,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$25/200","IsParsed":true}""" },
        { "$25/350", """{"Cost1920":25,"CostModern":350,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$25/350","IsParsed":true}""" },
        { "$3,75", """{"Cost1920":3.75,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3,75","IsParsed":true}""" },
        { "$3/35", """{"Cost1920":3,"CostModern":35,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3/35","IsParsed":true}""" },
        { "$3/9", """{"Cost1920":3,"CostModern":9,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3/9","IsParsed":true}""" },
        { "$30/300", """{"Cost1920":30,"CostModern":300,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$30/300","IsParsed":true}""" },
        { "$30/375", """{"Cost1920":30,"CostModern":375,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$30/375","IsParsed":true}""" },
        { "$30/75", """{"Cost1920":30,"CostModern":75,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$30/75","IsParsed":true}""" },
        { "$30/—", """{"Cost1920":30,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":true,"RawText":"$30/—","IsParsed":true}""" },
        { "$3000/20 000", """{"Cost1920":3000,"CostModern":20000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3000/20 000","IsParsed":true}""" },
        { "$3000/30 000", """{"Cost1920":3000,"CostModern":30000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3000/30 000","IsParsed":true}""" },
        { "$3000/50 000", """{"Cost1920":3000,"CostModern":50000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$3000/50 000","IsParsed":true}""" },
        { "$35/редкое", """{"Cost1920":35,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":true,"RawText":"$35/редкое","IsParsed":true}""" },
        { "$4/50", """{"Cost1920":4,"CostModern":50,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$4/50","IsParsed":true}""" },
        { "$40/200", """{"Cost1920":40,"CostModern":200,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$40/200","IsParsed":true}""" },
        { "$40/375", """{"Cost1920":40,"CostModern":375,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$40/375","IsParsed":true}""" },
        { "$40/редкое", """{"Cost1920":40,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":true,"RawText":"$40/редкое","IsParsed":true}""" },
        { "$400/1800", """{"Cost1920":400,"CostModern":1800,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$400/1800","IsParsed":true}""" },
        { "$45/100", """{"Cost1920":45,"CostModern":100,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$45/100","IsParsed":true}""" },
        { "$5/10", """{"Cost1920":5,"CostModern":10,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$5/10","IsParsed":true}""" },
        { "$5/50", """{"Cost1920":5,"CostModern":50,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$5/50","IsParsed":true}""" },
        { "$50/300", """{"Cost1920":50,"CostModern":300,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$50/300","IsParsed":true}""" },
        { "$7/75", """{"Cost1920":7,"CostModern":75,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$7/75","IsParsed":true}""" },
        { "$75/175", """{"Cost1920":75,"CostModern":175,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$75/175","IsParsed":true}""" },
        { "$75/600", """{"Cost1920":75,"CostModern":600,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$75/600","IsParsed":true}""" },
        { "$800/1500", """{"Cost1920":800,"CostModern":1500,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"$800/1500","IsParsed":true}""" },
        { "Нет", """{"Cost1920":null,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":true,"RawText":"Нет","IsParsed":true}""" },
        { "от $200 / $1600", """{"Cost1920":200,"CostModern":1600,"IsApproximate1920":true,"IsApproximateModern":false,"Unavailable1920":false,"UnavailableModern":false,"RawText":"от $200 / $1600","IsParsed":true}""" },
        { "—", """{"Cost1920":null,"CostModern":null,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":true,"RawText":"—","IsParsed":true}""" },
        { "—/$10", """{"Cost1920":null,"CostModern":10,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$10","IsParsed":true}""" },
        { "—/$1000", """{"Cost1920":null,"CostModern":1000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$1000","IsParsed":true}""" },
        { "—/$1100", """{"Cost1920":null,"CostModern":1100,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$1100","IsParsed":true}""" },
        { "—/$1500", """{"Cost1920":null,"CostModern":1500,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$1500","IsParsed":true}""" },
        { "—/$200", """{"Cost1920":null,"CostModern":200,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$200","IsParsed":true}""" },
        { "—/$2000", """{"Cost1920":null,"CostModern":2000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$2000","IsParsed":true}""" },
        { "—/$275", """{"Cost1920":null,"CostModern":275,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$275","IsParsed":true}""" },
        { "—/$2800", """{"Cost1920":null,"CostModern":2800,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$2800","IsParsed":true}""" },
        { "—/$300", """{"Cost1920":null,"CostModern":300,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$300","IsParsed":true}""" },
        { "—/$3000", """{"Cost1920":null,"CostModern":3000,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$3000","IsParsed":true}""" },
        { "—/$400", """{"Cost1920":null,"CostModern":400,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$400","IsParsed":true}""" },
        { "—/$425", """{"Cost1920":null,"CostModern":425,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$425","IsParsed":true}""" },
        { "—/$475", """{"Cost1920":null,"CostModern":475,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$475","IsParsed":true}""" },
        { "—/$500", """{"Cost1920":null,"CostModern":500,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$500","IsParsed":true}""" },
        { "—/$600", """{"Cost1920":null,"CostModern":600,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$600","IsParsed":true}""" },
        { "—/$650", """{"Cost1920":null,"CostModern":650,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$650","IsParsed":true}""" },
        { "—/$750", """{"Cost1920":null,"CostModern":750,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$750","IsParsed":true}""" },
        { "—/$895", """{"Cost1920":null,"CostModern":895,"IsApproximate1920":false,"IsApproximateModern":false,"Unavailable1920":true,"UnavailableModern":false,"RawText":"—/$895","IsParsed":true}""" },
    };
}
