# /// script
# dependencies = ["pillow"]
# ///
"""Иллюстрации книжного оружия → статика UI (src/CampaignManager.UI/wwwroot/img/weapons).

    uv run tools/export-weapon-art.py X:/Knowledge/CallOfCthulhu/weapons-art/generated

Исходники — PNG 1536×1024 вида <эпоха>/<slug>.png, slug = код без «weapon.» (weapon.thompson → thompson).
Берутся только коды из Core/Catalogs/WeaponCodes.cs; для кода сначала ищется classic/, потом modern/.
На выходе две WebP на код: <slug>.webp (960×640, раскрытая строка) и <slug>.thumb.webp (360×240, миниатюра),
и список кодов с картинкой — UI/Catalogs/WeaponArt.Codes.cs. Каталог картинок пересобирается целиком.
"""
import pathlib
import re
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
CODES = ROOT / 'src/CampaignManager.Core/Catalogs/WeaponCodes.cs'
OUT = ROOT / 'src/CampaignManager.UI/wwwroot/img/weapons'
LIST = ROOT / 'src/CampaignManager.UI/Catalogs/WeaponArt.Codes.cs'
SIZES = {'': 960, '.thumb': 360}
QUALITY = 80


def main(source: pathlib.Path) -> None:
    slugs = sorted(set(re.findall(r'new\("weapon\.([a-z0-9-]+)"', CODES.read_text(encoding='utf-8'))))
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob('*.webp'):
        old.unlink()

    done, missing = [], []
    for slug in slugs:
        png = next((p for era in ('classic', 'modern') if (p := source / era / f'{slug}.png').exists()), None)
        if png is None:
            missing.append(slug)
            continue
        image = Image.open(png).convert('RGB')
        for suffix, width in SIZES.items():
            height = round(width * image.height / image.width)
            image.resize((width, height), Image.LANCZOS).save(OUT / f'{slug}{suffix}.webp', 'WEBP', quality=QUALITY, method=6)
        done.append(slug)

    lines = ''.join(f'        "weapon.{s}",\n' for s in done)
    LIST.write_text(
        '// <auto-generated>tools/export-weapon-art.py</auto-generated>\n'
        'namespace CampaignManager.UI.Catalogs;\n\n'
        'public static partial class WeaponArt\n{\n'
        '    private static readonly HashSet<string> Codes = new(StringComparer.Ordinal)\n    {\n'
        f'{lines}    }};\n}}\n',
        encoding='utf-8', newline='\n')

    size = sum(f.stat().st_size for f in OUT.glob('*.webp')) // 1024
    print(f'{len(done)} картинок, {size} КБ; без картинки: {", ".join(missing) or "нет"}')


if __name__ == '__main__':
    main(pathlib.Path(sys.argv[1]))
