name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/shman4ik/campain-manager:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Pull the latest image
          docker pull ghcr.io/${{ github.repository }}:latest
          
          # Stop and remove the existing container if it exists
          docker stop campaign-manager || true
          docker rm campaign-manager || true
          
          # Run the new container with database connection string
          docker run -d --name campaign-manager \
            --restart unless-stopped \
            -p 8080:8080 \
            -e ConnectionStrings__DefaultConnection="${{ secrets.ConnectionStrings__DefaultConnection }}" \            
            -e CAMPAIGNMANAGER__AUTHENTICATION__GOOGLE__CLIENTID="${{ secrets.CAMPAIGNMANAGER__AUTHENTICATION__GOOGLE__CLIENTID }}" \
            -e CAMPAIGNMANAGER__AUTHENTICATION__GOOGLE__CLIENTSECRET="${{ secrets.CAMPAIGNMANAGER__AUTHENTICATION__GOOGLE__CLIENTSECRET }}" \
            -e ASPNETCORE_FORWARDEDHEADERS_ENABLED="true" \
            ghcr.io/shman4ik/campain-manager:latest
          
          # Reload Nginx to apply any changes
          sudo systemctl reload nginx
